### ISSUE TITLE
Assets is empty

### ISSUE THREAD

**Issue by alam121** [tuya/tuya-android-iot-app-sdk-sample#2]
Hi,

I'm trying to replicate this project, but the assets list is returning empty even though I have added the assets and authorized user. Any idea what is wrong?

**Comment by zlinoliver** [comment]
Hi @alam121 thanks for the feedbacks! Please double check if you have subscribed the following API products for you cloud project.

![](https://images.tuyacn.com/app/IoTAppSDK/api_products_size.png)
